"""Pydantic schemas for request/response validation."""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator
from .models import TaskStatus, Priority


# ============ Task Schemas ============

class TaskBase(BaseModel):
    """Base task schema."""
    title: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    priority: Priority = Priority.MEDIUM
    estimated_hours: Optional[float] = Field(None, ge=0)
    deadline: Optional[datetime] = None
    dependencies: List[int] = []


class TaskCreate(TaskBase):
    """Schema for creating a task."""
    pass


class TaskUpdate(BaseModel):
    """Schema for updating a task."""
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    priority: Optional[Priority] = None
    status: Optional[TaskStatus] = None
    estimated_hours: Optional[float] = Field(None, ge=0)
    deadline: Optional[datetime] = None


class TaskResponse(TaskBase):
    """Schema for task response."""
    id: int
    goal_id: int
    status: TaskStatus
    order: int
    created_at: datetime
    updated_at: datetime
    
    @field_validator('dependencies', mode='before')
    @classmethod
    def parse_dependencies(cls, v):
        """Parse dependencies from string or return list."""
        if v is None or v == "":
            return []
        if isinstance(v, str):
            # Parse comma-separated string to list of integers
            return [int(d.strip()) for d in v.split(",") if d.strip()]
        if isinstance(v, list):
            return v
        return []
    
    class Config:
        from_attributes = True


class TaskFromLLM(BaseModel):
    """Schema for task generated by LLM."""
    title: str
    description: str
    priority: str
    estimated_hours: float
    day_offset: int = Field(..., description="Days from start to deadline")
    dependencies: List[int] = Field(default=[], description="Indices of dependent tasks")


# ============ Goal Schemas ============

class GoalCreate(BaseModel):
    """Schema for creating a goal."""
    goal: str = Field(..., min_length=5, max_length=1000, description="The goal description")
    context: Optional[str] = Field(None, max_length=2000, description="Additional context")
    deadline_days: Optional[int] = Field(None, ge=1, le=365, description="Days to complete")


class GoalResponse(BaseModel):
    """Schema for goal response."""
    id: int
    goal_text: str
    context: Optional[str]
    deadline: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    tasks: List[TaskResponse] = []
    
    class Config:
        from_attributes = True


class GoalSummary(BaseModel):
    """Schema for goal list response."""
    id: int
    goal_text: str
    deadline: Optional[datetime]
    created_at: datetime
    task_count: int
    completed_count: int
    
    class Config:
        from_attributes = True


# ============ Plan Schemas ============

class PlanResponse(BaseModel):
    """Schema for generated plan response."""
    goal_id: int
    goal_text: str
    deadline: Optional[datetime]
    total_estimated_hours: float
    tasks: List[TaskResponse]
    reasoning: str = Field(..., description="LLM's reasoning for the breakdown")


class ErrorResponse(BaseModel):
    """Schema for error responses."""
    error: str
    detail: Optional[str] = None